<script setup>
import { computed, ref } from 'vue';

const menuOpen = ref(false);
const searchOpen = ref(false);
const search = ref('');
const cartCount = ref(0);

const categories = [
    { name: 'Honey', subtitle: 'Pure & natural', icon: '🍯', href: '/category/honey' },
    { name: 'Dates', subtitle: 'Naturally sweet', icon: '🌴', href: '/category/dates' },
    { name: 'Dry Food', subtitle: 'Wholesome pantry', icon: '🥜', href: '/category/dry-food' },
    { name: 'Masala', subtitle: 'Freshly ground', icon: '🌶️', href: '/category/masala' },
    { name: 'Tea', subtitle: 'A calm cup', icon: '🍵', href: '/category/tea' },
    { name: 'Nuts & Seeds', subtitle: 'Goodness in every bite', icon: '🌰', href: '/category/nuts-seeds' },
];

const products = [
    { name: 'Primal Gold', bangla: 'প্রাইমাল গোল্ড · Honey, Nuts & Herbal', price: '৳ 1,050', oldPrice: '৳ 1,200', badge: 'Best seller', image: 'https://cdn.falaqfood.com/uploads/media/2026/08/01a05135-6532-7173-8fce-069b93b0f86a.webp' },
    { name: 'Fermented Garlic & Honey', bangla: 'ফার্মেন্টেড গার্লিক হানি', price: '৳ 950', oldPrice: '৳ 1,100', badge: 'Popular', image: 'https://cdn.falaqfood.com/uploads/media/2026/08/01a05704-1d59-7f17-aa56-70f277bc2547.webp' },
    { name: 'রসুনজিরা', bangla: 'কালোজিরা, রসুন, মধু মিক্স', price: '৳ 390', oldPrice: '', badge: '', image: 'https://cdn.falaqfood.com/uploads/media/2026/06/019ef93a-f9df-7731-9976-0ba2c308205f.webp' },
    { name: 'Shilajit Honey', bangla: 'শিলাজিৎ মধু', price: '৳ 450', oldPrice: '৳ 500', badge: 'New', image: 'https://cdn.falaqfood.com/uploads/media/2026/09/01a07628-b6b6-7c3b-b0c4-86408d538941.webp' },
];

const visibleProducts = computed(() => {
    const term = search.value.trim().toLowerCase();
    return term ? products.filter((product) => `${product.name} ${product.bangla}`.toLowerCase().includes(term)) : products;
});

function addToCart() { cartCount.value += 1; }
function submitSearch() {
    if (search.value.trim()) window.location.href = `/search?keyword=${encodeURIComponent(search.value.trim())}`;
}
</script>

<template>
    <div class="storefront-shell mobile-bottom-space">
        <div class="hidden bg-falaq-700 text-white md:block">
            <div class="container-falaq flex h-[45px] items-center justify-between text-[11px] tracking-wide">
                <div class="flex items-center gap-5 opacity-95"><a href="tel:+8801700000000">☎ +880 1700 000000</a><a href="mailto:hello@falaqfood.com">✉ hello@falaqfood.com</a></div>
                <div class="flex items-center gap-4"><a href="/track-order">Track your order</a><span class="opacity-50">|</span><a href="/account/register">Become an Affiliate</a></div>
            </div>
        </div>

        <header class="border-b border-slate-100 bg-white">
            <div class="container-falaq flex h-[76px] items-center gap-4 md:h-[90px] md:gap-8">
                <button class="rounded-lg p-2 text-falaq-700 md:hidden" aria-label="Open menu" @click="menuOpen = true"><svg class="h-6 w-6" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M4 6h16M4 12h16M4 18h16" /></svg></button>
                <a href="/vue-preview" class="flex shrink-0 items-center gap-2 text-falaq-700" aria-label="Falaq Food home"><span class="grid h-10 w-10 place-items-center rounded-full bg-falaq-100 text-xl">🌿</span><span class="hidden font-display text-[25px] font-bold leading-none tracking-tight sm:block">falaq<span class="text-falaq-500">food</span></span></a>
                <form class="relative hidden min-w-0 flex-1 md:block" @submit.prevent="submitSearch"><input v-model="search" type="search" placeholder="Search products, categories..." class="h-11 w-full rounded-full border border-slate-200 bg-slate-50 px-5 pr-12 text-sm outline-none transition focus:border-falaq-500 focus:bg-white focus:ring-2 focus:ring-falaq-100"><button class="absolute right-1 top-1 grid h-9 w-9 place-items-center rounded-full bg-falaq-500 text-white" aria-label="Search"><svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg></button></form>
                <div class="ml-auto flex items-center gap-1 text-falaq-700 md:gap-3"><button class="grid h-10 w-10 place-items-center rounded-full hover:bg-falaq-50 md:hidden" aria-label="Search" @click="searchOpen = !searchOpen"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></svg></button><a href="/account/login" class="hidden items-center gap-2 rounded-full px-3 py-2 text-sm hover:bg-falaq-50 sm:flex"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.8-3.5 3-5.2 7-5.2s6.2 1.7 7 5.2"/></svg><span>Account</span></a><a href="/customer/checkout" class="relative grid h-10 w-10 place-items-center rounded-full hover:bg-falaq-50" aria-label="Cart"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/><path d="M2.5 3h2l2.1 11.3a1.7 1.7 0 0 0 1.7 1.4h8.2a1.7 1.7 0 0 0 1.65-1.3L20.3 7H6"/></svg><span v-if="cartCount" class="absolute -right-0.5 -top-0.5 grid h-4 min-w-4 place-items-center rounded-full bg-falaq-500 px-1 text-[10px] font-bold text-white">{{ cartCount }}</span></a></div>
            </div>
            <form v-if="searchOpen" class="container-falaq pb-3 md:hidden" @submit.prevent="submitSearch"><input v-model="search" autofocus type="search" placeholder="Search products..." class="h-11 w-full rounded-full border border-slate-200 bg-slate-50 px-5 text-sm outline-none focus:border-falaq-500"></form>
        </header>

        <nav class="hidden border-b border-falaq-700/20 bg-falaq-700 text-white md:block"><div class="container-falaq flex h-11 items-center justify-center gap-10 text-sm font-medium"><a class="hover:text-falaq-100" href="/vue-preview">Home</a><a class="hover:text-falaq-100" href="/shop">Shop</a><a class="hover:text-falaq-100" href="/offers">Offers</a><a class="hover:text-falaq-100" href="/about-us">About us</a><a class="hover:text-falaq-100" href="/blog">Blog</a><a class="hover:text-falaq-100" href="/contact-us">Contact</a></div></nav>

        <main>
            <section class="hero-wash border-b border-falaq-100"><div class="container-falaq grid min-h-[470px] items-center gap-8 py-10 md:grid-cols-[1.08fr_.92fr] md:py-14 lg:min-h-[540px]"><div class="max-w-xl"><p class="mb-4 text-xs font-bold uppercase tracking-[.24em] text-falaq-600">Pure food, honest living</p><h1 class="font-display text-4xl font-bold leading-[1.08] text-falaq-900 sm:text-5xl lg:text-6xl">Naturally good food for a healthier you.</h1><p class="mt-5 max-w-lg text-base leading-7 text-slate-600 md:text-lg">Discover carefully sourced honey, dates, nuts, tea and pantry essentials delivered fresh to your door.</p><div class="mt-8 flex flex-wrap gap-3"><a href="/shop" class="rounded-full bg-falaq-500 px-7 py-3 text-sm font-bold text-white shadow-lg shadow-falaq-500/20 transition hover:bg-falaq-700">Shop now</a><a href="/offers" class="rounded-full border border-falaq-500 bg-white/60 px-7 py-3 text-sm font-bold text-falaq-700 transition hover:bg-white">View offers</a></div><div class="mt-9 flex flex-wrap gap-x-6 gap-y-2 text-xs font-medium text-slate-500"><span>✓ 100% natural products</span><span>✓ Fast delivery</span><span>✓ Secure checkout</span></div></div><div class="relative mx-auto w-full max-w-[530px]"><div class="absolute -left-4 top-9 h-24 w-24 rounded-full bg-falaq-100 blur-2xl"></div><div class="absolute -right-4 bottom-2 h-32 w-32 rounded-full bg-amber-100 blur-2xl"></div><div class="relative overflow-hidden rounded-[32px] border-8 border-white bg-white shadow-soft"><img class="h-[310px] w-full object-cover sm:h-[380px]" src="https://cdn.falaqfood.com/uploads/media/2026/09/01a05bcc-f528-7951-95f1-9d3df069ff6d.webp" alt="Organic honey and natural food"><div class="absolute bottom-4 left-4 right-4 flex items-center justify-between rounded-2xl bg-white/90 p-4 backdrop-blur"><div><p class="text-xs text-slate-500">Featured pick</p><p class="font-display text-lg font-bold text-falaq-900">Primal Gold</p></div><span class="rounded-full bg-falaq-100 px-3 py-1 text-xs font-bold text-falaq-700">Best seller</span></div></div></div></div></section>

            <section class="container-falaq py-10 md:py-14"><div class="mb-6 flex items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-falaq-500">Browse by category</p><h2 class="mt-2 font-display text-3xl font-bold text-falaq-900">Shop your favourites</h2></div><a href="/shop" class="hidden text-sm font-bold text-falaq-600 hover:text-falaq-900 sm:block">View all →</a></div><div class="hide-scrollbar -mx-1 flex gap-3 overflow-x-auto pb-2 sm:grid sm:grid-cols-3 sm:overflow-visible lg:grid-cols-6"><a v-for="category in categories" :key="category.name" :href="category.href" class="group min-w-[145px] rounded-2xl border border-slate-100 bg-white p-4 text-center shadow-sm transition hover:-translate-y-1 hover:border-falaq-100 hover:shadow-soft"><span class="mx-auto grid h-16 w-16 place-items-center rounded-full bg-falaq-50 text-3xl transition group-hover:bg-falaq-100">{{ category.icon }}</span><h3 class="mt-3 text-sm font-bold text-falaq-900">{{ category.name }}</h3><p class="mt-1 text-[11px] text-slate-500">{{ category.subtitle }}</p></a></div></section>

            <section class="bg-white py-10 md:py-14"><div class="container-falaq"><div class="mb-6 flex items-end justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-falaq-500">Handpicked for you</p><h2 class="mt-2 font-display text-3xl font-bold text-falaq-900">Featured products</h2></div><a href="/shop" class="hidden text-sm font-bold text-falaq-600 hover:text-falaq-900 sm:block">Shop all →</a></div><div v-if="visibleProducts.length" class="grid grid-cols-2 gap-3 sm:grid-cols-2 sm:gap-5 lg:grid-cols-4"><article v-for="product in visibleProducts" :key="product.name" class="group relative overflow-hidden rounded-2xl border border-slate-100 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-soft"><a href="/product/sundarban-honey-1kg" class="product-card-image relative block overflow-hidden"><img :src="product.image" :alt="product.name" class="h-full w-full object-cover transition duration-500 group-hover:scale-105"><span v-if="product.badge" class="absolute left-3 top-3 rounded-full bg-falaq-500 px-2.5 py-1 text-[10px] font-bold text-white">{{ product.badge }}</span></a><div class="p-3 sm:p-4"><p class="text-[11px] text-slate-500">{{ product.bangla }}</p><h3 class="mt-1 line-clamp-2 min-h-10 text-sm font-bold leading-5 text-falaq-900 sm:text-base">{{ product.name }}</h3><div class="mt-3 flex items-end justify-between gap-2"><div><span class="text-base font-bold text-falaq-700">{{ product.price }}</span><del v-if="product.oldPrice" class="ml-1 text-[10px] text-slate-400">{{ product.oldPrice }}</del></div><button @click.prevent="addToCart" class="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-falaq-50 text-falaq-700 transition hover:bg-falaq-500 hover:text-white" aria-label="Add to cart">+</button></div></div></article></div><p v-else class="rounded-2xl bg-falaq-50 p-8 text-center text-sm text-slate-500">No products matched your search.</p></div></section>

            <section class="container-falaq py-10 md:py-14"><div class="grid gap-4 sm:grid-cols-3"><div class="rounded-2xl bg-falaq-50 p-5"><span class="text-2xl">🌱</span><h3 class="mt-3 font-bold text-falaq-900">Naturally sourced</h3><p class="mt-1 text-xs leading-5 text-slate-500">We choose clean, honest ingredients from trusted sources.</p></div><div class="rounded-2xl bg-amber-50 p-5"><span class="text-2xl">🚚</span><h3 class="mt-3 font-bold text-falaq-900">Reliable delivery</h3><p class="mt-1 text-xs leading-5 text-slate-500">Fresh products delivered safely across Bangladesh.</p></div><div class="rounded-2xl bg-sky-50 p-5"><span class="text-2xl">💚</span><h3 class="mt-3 font-bold text-falaq-900">Made for wellbeing</h3><p class="mt-1 text-xs leading-5 text-slate-500">Everyday choices that make healthy living simple.</p></div></div></section>
        </main>

        <footer class="bg-falaq-900 py-10 text-white md:py-14"><div class="container-falaq grid gap-8 md:grid-cols-[1.4fr_1fr_1fr_1.3fr]"><div><div class="flex items-center gap-2"><span class="grid h-9 w-9 place-items-center rounded-full bg-white/15 text-lg">🌿</span><span class="font-display text-2xl font-bold">falaq<span class="text-falaq-500">food</span></span></div><p class="mt-4 max-w-xs text-sm leading-6 text-white/65">Natural and organic food delivered with care.</p></div><div><h3 class="font-bold">Quick links</h3><div class="mt-4 grid gap-2 text-sm text-white/65"><a href="/shop" class="hover:text-white">Shop</a><a href="/offers" class="hover:text-white">Offers</a><a href="/about-us" class="hover:text-white">About us</a></div></div><div><h3 class="font-bold">Customer care</h3><div class="mt-4 grid gap-2 text-sm text-white/65"><a href="/track-order" class="hover:text-white">Track order</a><a href="/contact-us" class="hover:text-white">Contact us</a><a href="/return-refund-policy" class="hover:text-white">Return policy</a></div></div><div><h3 class="font-bold">Stay connected</h3><p class="mt-4 text-sm leading-6 text-white/65">Get new offers and healthy food tips in your inbox.</p><div class="mt-3 flex overflow-hidden rounded-full bg-white"><input class="min-w-0 flex-1 bg-transparent px-4 py-2 text-sm text-slate-800 outline-none" placeholder="Your email"><button class="bg-falaq-500 px-4 text-sm font-bold">Join</button></div></div></div><div class="container-falaq mt-10 border-t border-white/10 pt-5 text-xs text-white/45">© 2026 Falaq Food. All rights reserved.</div></footer>

        <div v-if="menuOpen" class="fixed inset-0 z-50 bg-slate-900/40 md:hidden" @click.self="menuOpen = false"><aside class="h-full w-[82%] max-w-sm bg-white p-6 shadow-2xl"><div class="flex items-center justify-between"><span class="font-display text-2xl font-bold text-falaq-700">falaqfood</span><button class="text-2xl text-slate-500" @click="menuOpen = false">×</button></div><div class="mt-8 grid gap-1 text-base font-medium"><a v-for="link in [{label:'Home',href:'/vue-preview'},{label:'Shop',href:'/shop'},{label:'Offers',href:'/offers'},{label:'About us',href:'/about-us'},{label:'Blog',href:'/blog'},{label:'Contact',href:'/contact-us'}]" :key="link.label" :href="link.href" class="rounded-xl px-4 py-3 hover:bg-falaq-50">{{ link.label }}</a></div></aside></div>
        <nav class="fixed bottom-0 left-0 right-0 z-40 flex h-[78px] items-center justify-around border-t border-slate-200 bg-white/95 px-2 pb-[env(safe-area-inset-bottom)] shadow-[0_-8px_24px_rgba(0,0,0,.06)] backdrop-blur md:hidden"><a href="/vue-preview" class="flex flex-col items-center gap-1 text-[10px] font-medium text-falaq-700"><span class="text-lg">⌂</span>Home</a><a href="/shop" class="flex flex-col items-center gap-1 text-[10px] font-medium text-slate-500"><span class="text-lg">⌕</span>Shop</a><a href="/customer/checkout" class="relative flex flex-col items-center gap-1 text-[10px] font-medium text-slate-500"><span class="text-lg">🛒</span>Cart<span v-if="cartCount" class="absolute -right-2 -top-1 grid h-4 min-w-4 place-items-center rounded-full bg-falaq-500 px-1 text-[9px] text-white">{{ cartCount }}</span></a><a href="/account/login" class="flex flex-col items-center gap-1 text-[10px] font-medium text-slate-500"><span class="text-lg">♙</span>Account</a></nav>
    </div>
</template>
